# Stage 1: Build the application
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Copy only the project file and restore dependencies
COPY LiberacaoCredito.Api/LiberacaoCredito.Api.csproj ./
RUN dotnet restore

# Copy the remaining source code
COPY . ./

# Build the application
RUN dotnet publish -c Release -o out /app/LiberacaoCredito.Api/LiberacaoCredito.Api.csproj

# Stage 2: Build the runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app

# Copy the published output from the build stage
COPY --from=build-env /app/out .

# Expose the port that the application will run on
EXPOSE 80

# Define the entry point for the application
ENTRYPOINT ["dotnet", "LiberacaoCredito.Api.dll"]
